### ISSUE TITLE
为啥运行不起来呀?

### ISSUE THREAD

**Issue by littleheary** [timwhitez/crawlergo_x_XRAY#4]
运行
python3 launcher_new.py
等一会儿就自动结束了。没有任何报错，也不知道这是咋回事。

**Comment by timwhitez** [comment]
检查一下，chrome路径填写正确了吗，targets.txt/crawlergo执行文件和launcher_new.py是否在同一个文件，crawlergo空文件夹是否删除，尝试在targets.txt的url前面多加一行空格。

**Comment by timwhitez** [comment]
还有就是py3的request库是否安装了

**Comment by littleheary** [comment]
用旧版的luncher.py可以工作，新版的就不行。

**Comment by timwhitez** [comment]
看看是不是crawlergo没更新到最新版，如果不是的话我也没啥好办法了就用launcher吧这个速度还快点

**Comment by sv3nbeast** [comment]
> 运行
> python3 launcher_new.py
> 等一会儿就自动结束了。没有任何报错，也不知道这是咋回事。

你应该是用的windows，将第29行代码	cmd = ["./crawlergo", "-c"       改成     	cmd = ["crawlergo.exe", "-c"  就可以了
