### ISSUE TITLE
subprocess方法的communicate()函数会卡住

### ISSUE THREAD

**Issue by MrPointSun** [timwhitez/crawlergo_x_XRAY#6]
### subprocess方法的communicate()函数会卡住。
command命令在powershell能成功执行，但是放到subprocess的communicate()就会卡死。
我自己写了个test，用command命令会卡死，用dir/b命令就不会卡。

```
#!/usr/bin/python3
\# coding: utf-8
import simplejson
import threading
import subprocess
import requests
import warnings
warnings.filterwarnings(action='ignore')

def runcmd():
    command = ["./crawlergo", "-c", "D:\tools\crawlergo_x_XRAY\chromium\chrome.exe","-t", "20","-f","smart","--fuzz-path", "--output-mode", "json", "http://testphp.vulnweb.com/"]
    #command = ['dir','/b']
    #print(command)
    ret = subprocess.Popen(command, stdout=subprocess.PIPE,stderr=subprocess.PIPE)
    output, error = ret.communicate()
    print(output.decode('gbk'))
    print(error.decode('gbk'))

#runcmd(["dir","/b"])#序列参数
#runcmd("exit 1")#字符串参数

runcmd()
```
请问这个是这个函数的bug吗?还是我8g内存太小了？
有没有解决方法？

**Comment by timwhitez** [comment]
可以试试改成check_ouptut()函数。
    try:
        output = subprocess.check_output(cmd, timeout=1800)
    except:
        return None

**Comment by MrPointSun** [comment]
> 可以试试改成check_ouptut()函数。
> try:
> output = subprocess.check_output(cmd, timeout=1800)
> except:
> return None

谢谢，用check_output()看了下报错，发现了问题所在。
chrome.exe 的路径只能是相对路径，绝对路径会报错找不到文件。
将路径换成相对路径便可正常运行。
